viewer: optional user-defined markdown splash screen
ldgallery/ldgallery pull request #304
Opened 2021-07-03 03:07 UTC by zeroinformatique

GitHub: closes #284

2021-07-03 17:51 UTC, pacien requested changes
Here are some remarks, mainly simplifying things.
Please address them and request a new review from me before merging, since it's a big chunk.

Otherwise, I saw no technical quirk when testing this :+1:

2021-07-03 17:51 UTC, pacien commented on viewer/ldgallery-viewer.7.md
> +```
The example needs to be updated accordingly to the other suggestions.
Beside that,

```suggestion
# CONFIGURATION EXAMPLE

Viewer __config.json__:

```json
```

2021-07-03 17:51 UTC, pacien commented on viewer/ldgallery-viewer.7.md
> +
Here are a few changes for the documentation for clarity and consistency with
the conventions used everywhere else.

This also allows some simplifications in the code.

* `splashScreen.dontshoagainUID` is not needed since some timestamp or other
  version tag can already be supplied in the resource URL by appending some
  query such as `?20210703` at the end.

* `splashScreen.style` is not needed since styles can already be provided in the
  Markdown file itself. For example:

  `splashscreen.md`:

  ```md
  <style>
  #mySplashScreen { max-width: 200px; }
  </style>
  <div id="mySplashScreen">

  # Hello

  Welcome to my gallery.

  </div>
  ```

* `splashScreen.buttonValidateLabel` does not validate anything. A better name
  could be either "acknowledge", "dismiss", or "close".
  The first one is more explicit.


Note that this modified list of keys should be moved with the other ones, above
the preceeding paragraph about alternative configuration files.

Verbatim suggestion below:

```suggestion
splashScreen.resource
: Absolute or relative URL to a document to optionally display as a notice when
  entering the gallery for the first time.

  The user is prompted to explicitly acknowledge such notice before being
  allowed to browse the gallery and view its items.

  Once acknowledged, the notice is not shown again unless its resource URL has
  changed.

  Rich text formatting is possible through the use of the
  [GitHub Flavoured Markdown syntax][GFM].
  Inline HTML and CSS are also supported.

  [GFM]: https://github.github.com/gfm/

splashScreen.acknowledgeButtonLabel
: Label for the modal dismissal button shown below the notice.
  Defaults to "Close".
```

2021-07-03 17:51 UTC, pacien commented on viewer/src/views/SplashScreen.vue
> +}
It would be better to extract the normalised generic style to a separate CSS file, which could then be used to display other embedded MD and HTML resources. I think some of the definitions here are already covered in usual CSS normalisers.

Markdown-related things could also be extracted to their own component, which will be useful for the Markdown item handler.

Note that the title elements have correct margins around them, but also an undesirable internal line height:

![16253344227633](https://user-images.githubusercontent.com/1449319/124362809-8fdefe00-dc37-11eb-9768-e8b6f8917b71.png)

2021-07-03 17:51 UTC, pacien commented on viewer/src/views/SplashScreen.vue
> +}
That default minimum width is arbitrary and not necessary.
It makes the button ridiculously wide with the default label value.
Not everyone is a fan of Windows 8's style.

There is also some missing padding/margin below the button when the notice's text is long enough to cause the box to scroll:

![16253343481887](https://user-images.githubusercontent.com/1449319/124362769-48f10880-dc37-11eb-8ded-bb4eb9f55cce.png)



The name of the class should also match the name of the parameter.

```suggestion
.buttonAcknowledge {
  align-self: center;
}
```

2021-07-03 21:27 UTC, zeroinformatique commented
Type: "markdown" in implemented.
The compiler can detect and push them to the gallery now.

2021-07-03 21:53 UTC, zeroinformatique commented on viewer/ldgallery-viewer.7.md
> +
> splashScreen.dontshoagainUID is not needed since some timestamp

The compiler has no control over the configuration, this can't be supplied.
Also, the user may not want to reset the SplashScreen for small updates.

> splashScreen.style is not needed since styles can already be provided in the Markdown file itself.

I am not certain about this. The style is applied to the parent DIV, Markdown has no control over it.
I prefer to leave this functionality in for now.

> splashScreen.buttonValidateLabel does not validate anything.

I'll rename it to "acknowledge"

I used your suggestions to rework the documentation.

2021-07-03 21:59 UTC, zeroinformatique commented on viewer/src/views/SplashScreen.vue
> +}
I unified the Markdown component so the CSS is standard only for Markdown and nothing else.
HTML resources should be pushed to an IFrame and CSS won't be our responsibility in that case.

About the CSS itself (line-height, etc); I suggest you try to fiddle with it and suggest a push later.

2021-07-03 22:04 UTC, zeroinformatique commented on viewer/src/views/SplashScreen.vue
> +}
> That default minimum width is arbitrary and not necessary.

The button, by default, is too small and not visible enough.
310px isn't arbitrary, it slightly smaller than a mobile screen (320px), so it looks pretty good on mobile.

> There is also some missing padding/margin below the button when the notice's text is long enough to cause the box to scroll.

Weird, I have padding all around the SplashScreen. You'll have to show me your screen.

Okay for the button's name.

2021-07-04 15:51 UTC, pacien commented
I extracted the markdown renderer and item handler stub to a separate pull request so that they can be worked on independently.
The changes related to CSS modules have also been merged to develop and this branch has been cleanly rebased accordingly.

2021-07-04 15:52 UTC, pacien commented on viewer/src/views/SplashScreen.vue
> +}
> > There is also some missing padding/margin below the button when the notice's text is long enough to cause the box to scroll.
> 
> Weird, I have padding all around the SplashScreen. You'll have to show me your screen.

You can see it in the screenshot in the previous message you replied to. You can reproduce it by putting a long document in "splashscreen.md" to cause an overflow. Scrolling at the bottom, you'll see that this padding/margin is oddly not affecting the bottom of the button. I have no idea of why that is the case.

2021-07-04 16:00 UTC, pacien commented on viewer/ldgallery-viewer.7.md
> +
> > splashScreen.dontshoagainUID is not needed since some timestamp
> 
> The compiler has no control over the configuration, this can't be supplied.

The user can manually append the arbitrary value in the URL as a query parameter.
(This has nothing to do with the automatic time-stamping and is independent from the compiler).

To clarify, in my understanding,

```json
{
  "resource": "splashscreen.md",
  "dontshowagainUID": "tos-v1"
}
```

seems functionally equivalent to:

```json
{
  "resource": "splashscreen.md?tos-v1"
}
```

Could you confirm that both have the same effects?
If so, the extra key seems superfluous.


> Also, the user may not want to reset the SplashScreen for small updates.

They can keep the same file name and not update the query parameter for small updates.


> > splashScreen.style is not needed since styles can already be provided in the Markdown file itself.
> 
> I am not certain about this. The style is applied to the parent DIV, Markdown has no control over it.
> I prefer to leave this functionality in for now.

In which case should the user be able to apply styling rules to the outer div element?
What cases aren't covered with simply applying style to the inner element from within the markdown file?

2021-07-04 16:03 UTC, pacien commented on viewer/ldgallery-viewer.7.md
> +: Displays an information notice before opening the gallery (see below).
This entry should be placed above the paragraph immediately preceeding it, to be with the other keys.

2021-07-04 16:04 UTC, pacien commented on viewer/ldgallery-viewer.7.md
> +  [GFM]: https://github.github.com/gfm/
This should be placed within the definition which uses the link reference, otherwise the link isn't properly rendered with some markdown processors.

2021-07-04 16:35 UTC, zeroinformatique commented on viewer/ldgallery-viewer.7.md
> +
> Could you confirm that both have the same effects?

I could store the whole URL to the localStorage instead, but we will still need a key to ask if we want to remember when the user has acknowledged the notice. I know some users want the message to appear every time. This is not possible with this simplification.

Also, I don't like the idea to add a cache invalidation manually; if the user forgets to add it, the viewers may get an older notice; this can be dangerous and confusing.

> They can keep the same file name and not update the query parameter for small updates.

I'm not for arbitrary behavior change based on the structure of the URL.
I'm open to suggestions, but that one doesn't seem like a good idea to me.

> In which case should the user be able to apply styling rules to the outer div element?

I do it on my gallery to change how the button appears. The button isn't inside the Markdown.

2021-07-04 16:38 UTC, zeroinformatique commented on viewer/src/views/SplashScreen.vue
> +}
This is a bug in FireFox. Let's FFox it.

2021-07-04 16:40 UTC, zeroinformatique commented on viewer/ldgallery-viewer.7.md
> +: Displays an information notice before opening the gallery (see below).
This is the case, no?

2021-07-04 16:41 UTC, zeroinformatique commented on viewer/ldgallery-viewer.7.md
> +  [GFM]: https://github.github.com/gfm/
Okay, since you seem to know how to do it, can you do it?

2021-07-05 15:57 UTC, zeroinformatique commented on viewer/ldgallery-viewer.7.md
> +
After phone call, we decide to leave it as-is for now, and just rename `dontshowagainUID` to `acknowledgementKey` and detail how arbitrary this key is in the documentation.

2021-07-05 17:07 UTC, pacien commented on viewer/src/views/SplashScreen.vue
> +}
Bug observed with Firefox 78.11.0esr, but gone on 89.0.2.
Since it's not a critical issue impeding the use of the software, we can just ignore it.

2021-07-05 17:15 UTC, pacien approved these changes
LGTM.

2021-07-05 18:19 UTC, merged